import { BOOKING_STEPS } from "types/booking";

export const steps = [
  BOOKING_STEPS.TASK,
  BOOKING_STEPS.DESCRIPTION,
  BOOKING_STEPS.PROVIDERS,
  BOOKING_STEPS.SCHEDULE,
  BOOKING_STEPS.ADDRESS,
];
